### ISSUE TITLE
Save api key

### ISSUE THREAD

**Issue by bluetibius** [atmoner/TwitWork#1]
Lors du lancement de l'application, le popup demande d'insérer les clé api de twitter. 

Le bouton save ne fait rien, il n'y as vraisemblablement rien de prévu quand on clique sur save

**Comment by atmoner** [comment]
@bluetibius Bien vu!! J'ai oublier d'ajouter l'id du button.... La fonction était prévu [ici](https://github.com/atmoner/TwitWork/blob/master/lib/menu.js#L32) 
Corrigé ici: https://github.com/atmoner/TwitWork/commit/250ada60c4923bf62964e63e6c1f9a308c36a671

Merci!! =)

**Comment by bluetibius** [comment]
Tu as changé je crois le mauvais, c'est celui à la ligne 126 qu'il faut pour l'API Twitter :-)

**Comment by atmoner** [comment]
> Tu as changé je crois le mauvais, c'est celui à la ligne 126 qu'il faut pour l'API Twitter :-)

Je suis un gros boulet! Merci @bluetibius c'est corrigé

**Comment by bluetibius** [comment]
Je vois ce genre de chose parce que je fait les mêmes. Je sais donc quoi chercher :-p
