### ISSUE TITLE
Twitter API issues

### ISSUE THREAD

**Issue by caretak3r** [atmoner/TwitWork#10]
Not sure of the extent of the problem, maybe due to breaking changes (from the events a few days ago), the status page still gives us POST degradation, but I think they are making some serious restrictions until they get the situation under control: 

https://api.twitterstat.us/

**Comment by atmoner** [comment]
@caretak3r I don't have the impression that the endpoints used by twitwork are touching, for me, it works ...
do you manage to make twitwork work?
