### ISSUE TITLE
[Feature request] Better resolution of screeenshots + SVG + GEXF

### ISSUE THREAD

**Issue by secou** [atmoner/TwitWork#11]
Hi atmon3r and thanks for Twitwork !
It would be so interesting to have a better screenshot resolution, perhaps could we have the ability to choose width, height and resolution... 
And what about having other export formats like SVG and GEXF?

**Comment by atmoner** [comment]
hi @secou !
you're right, it would be good to have a better resolution ...
I am using the npm html-to-image lib to export the image, I saw that there is the possibility of exporting in several formats 
Check it here: https://www.npmjs.com/package/html-to-image

I would test this tonight ;)

**Comment by secou** [comment]
Waouh ! Great! Thanks!
