### ISSUE TITLE
Run TwitWork inside a browser

### ISSUE THREAD

**Issue by Gil-Epshtain** [atmoner/TwitWork#13]
Is there a way to run TwitWork inside a browser on the client-side? without any installation of the user? Or is it a desktop-only application?
If there is a way to run this tool in the browser where could I find an API for this tool?

**Comment by atmoner** [comment]
Hello @Gil-Epshtain 
TwitWork is a desktop-only program ...
I tried to adapt a script to launch it from a browser, I had succeeded for a single request but it was not possible to launch several twitter streams at the same time...

**Comment by Gil-Epshtain** [comment]
@atmoner 
Thank you for your quick answer :-)
