### ISSUE TITLE
Vis-network peer

### ISSUE THREAD

**Issue by slappyslap** [atmoner/TwitWork#3]
## Erreur

Probleme d'installation vis-network peer (vis-data, vis-utils)

## Steps to Reproduce the Problem

  1. git clone
  1. npm install
  1. npm start

## Correction

Changement de la version de vis-network dans le package.json par `=7.3.4`

## Specifications

  - Version: 1.0.0
  - Platform: Solus
  - kernel: 5.5.7-150.current 
  - Node : v12.15.0
  - Npm: 6.13.4

**Comment by GuillaumeASSIER** [comment]
Même problème et une fois la manip effectuée l'application fonctionne correctement. Je viens de commit une version avec le package.json corrigé ainsi que electron mise à jour sur mon github ~> [https://github.com/Sykursen/TwitWork](https://github.com/Sykursen/TwitWork). Je peux faire une pull request si ça intéresse.

**Comment by atmoner** [comment]
@Sykursen tu peux y aller pour le pull, pas de souci je vérifiais ça demain...
C'est encore en développement donc si tu trouves des bug où des idées n'hésite pas.
Merci 👍

**Comment by GuillaumeASSIER** [comment]
Voila, je viens de faire la pull request. Bonne relecture [https://github.com/atmoner/TwitWork/pull/5](https://github.com/atmoner/TwitWork/pull/5)

**Comment by atmoner** [comment]
Je valide le push demain, je n'avais même pas vu qu'electron avait maj ^^
Nickel!! 
Du coup ca ta reglé ton souci pour ajouter tes clefs api?  tu as pu tester le stream?

**Comment by GuillaumeASSIER** [comment]
Lors du lancement de l'application, le popup de demande de clef apparait bien.  J'attends la validation de twitter pour récupérer a clef d'api.

**Comment by atmoner** [comment]
Erf... Ca peu être long! Tres long... 
Je te ferais une clef api temporaire demain, tu pourras l'utiliser 24h 😉
