### ISSUE TITLE
The app does not launch

### ISSUE THREAD

**Issue by githubglob** [atmoner/TwitWork#7]
Hi!
After installing every suggested tool according to README, the application does not launch.
It keeps stucked in the API keys introduction interface. When I press start, the button does not seem to work. From time to time, the Windows sand clock appears and disappears. No advance.
Windows 10. Old Twitter API keys (as far as I know, working ones).

Many thanks in advance,

**Comment by atmoner** [comment]
hello @githubglob,
Indeed, several people have told me about this problem.
It is due to a bad compilation on my part of the windows version.

I updated the windows version right now, delete the current version you have on your computer and download it again here:
https://github.com/atmoner/TwitWork/releases/download/1.2/TwitWork1.2-win32-x64.zip.zip

The problem should be solved!

**Comment by githubglob** [comment]
Hi.
Thanks for your help.
It goes to the next screen, but it gives no data when you provide a hashtag, sentence or user. No reaction in stabilice or options.
¿?
I will try in Ubuntu.
Glob

**Comment by atmoner** [comment]
Try to debug it please
In the menu -> view -> toggle developer tool -> debug console
you should have an error.

If you don't have an error, your API key is no longer valid :/

**Comment by githubglob** [comment]
There is no error but three warnings.
All of them say "DevTools failed to parse Source Map", and then the same link to a file with three different endings:  vis-network.min.js.maps; uri.all.js.map;  and performance-now.js.map. 
So it is the API key, you think?
Thanks.

**Comment by atmoner** [comment]
yes I think the problem comes from your keys, try to regenerate the token access from your Twitter dev account here:
https://developer.twitter.com/

**Comment by githubglob** [comment]
I am afraid I did that before and did not work. I would try again, but the tool does not allow to introduce the APIs again. Not in Reload or Force reload...

**Comment by atmoner** [comment]
to edit the API keys in TwitWork, look in the file:
`C:\Users\<you>\AppData\Local\TwitWork\config.json`

**Comment by githubglob** [comment]
It worked!!!
At the beginning I did not find it because TwitWork is inside "roaming", not "local", in my PC. Just saying in case it may help another user.
C:\Users\MyPC\AppData\Roaming\TwitWork
You just can save data on the screen in .jpg, can't you? Not in csv or other format, I guess.
It is super helpful, anyway. Thank you so much!!!
G.

**Comment by atmoner** [comment]
you can use the screen button next to the start button in tweet work.
or used a Windows screen capture tool
